<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	  <Version>1.0.8</Version>
	  <ApplicationIcon>Assets\icon.ico</ApplicationIcon>
	  <PublishReferencesDocumentationFiles>false</PublishReferencesDocumentationFiles>
  </PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<NoWarn>CA1416;</NoWarn>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<NoWarn>CA1416;</NoWarn>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="Assets\github.png" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Interop.IWshRuntimeLibrary" Version="1.0.1" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
		<PackageReference Include="SerializableHttps" Version="1.2.9" />
		<PackageReference Include="WPF-UI" Version="4.3.0" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
		<PackageReference Include="WPF-UI.Tray" Version="4.3.0" />
		<PackageReference Include="ToolsSharp" Version="1.1.14" />
	</ItemGroup>

	<ItemGroup>
	  <Resource Include="Assets\github.png" />
	  <Resource Include="Assets\icon1.png" />
	  <Resource Include="Assets\icon2.png" />
	  <Resource Include="Assets\icon.ico" />
	</ItemGroup>

	<ItemGroup>
	  <Page Include="App.xaml" />
	</ItemGroup>

</Project>
