<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	  <Version>1.0.14</Version>
	  <ApplicationIcon>Assets\icon.ico</ApplicationIcon>
	  <PublishReferencesDocumentationFiles>false</PublishReferencesDocumentationFiles>
	  <SignAssembly>False</SignAssembly>
	  <Title>QuickTerm</Title>
	  <Authors>Kristian Skov</Authors>
	  <Description>A small project to make shortcuts to running terminal commands</Description>
	  <PackageProjectUrl>https://github.com/kris701/QuickTerm</PackageProjectUrl>
	  <PackageReadmeFile>README.md</PackageReadmeFile>
	  <PackageIcon>icon.png</PackageIcon>
	  <RepositoryUrl>https://github.com/kris701/QuickTerm</RepositoryUrl>
	  <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
  </PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<NoWarn>CA1416;</NoWarn>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<NoWarn>CA1416;</NoWarn>
	</PropertyGroup>

	<ItemGroup>
	  <None Include="..\LICENSE.txt">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	  <None Include="..\README.md">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
		<PackageReference Include="WindowsShortcutFactory" Version="1.2.0" />
		<PackageReference Include="WPF-UI" Version="4.3.0" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
		<PackageReference Include="WPF-UI.Tray" Version="4.3.0" />
	</ItemGroup>

	<ItemGroup>
	  <Resource Include="Assets\github.png" />
	  <Resource Include="Assets\icon.png" />
	  <Resource Include="Assets\icon.ico" />
	</ItemGroup>

	<ItemGroup>
	  <Page Include="App.xaml" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="Assets\icon.png">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	</ItemGroup>

</Project>
